platform :ios, '7.0'

pod 'TTTAttributedLabel'
pod 'AsyncImageDownloader', '~> 1.0.0'
pod 'DMActivityInstagram', '0.0.3'
pod 'Foursquare-API-v2', '~> 1.4.0'
pod 'Foursquare-iOS-API', '~> 2.0'
pod 'Reachability', '~> 3.1.1'
pod 'FlatUIKit'
pod 'Facebook-iOS-SDK', '~> 3.12.0'
pod 'DYRateView', '~> 0.0.2'
pod 'AFNetworking', '~> 2.1.0'
pod 'MACachedImageView', '~> 1.1.2'
pod 'TMCache', '~> 1.2.0'
pod 'LRImageManager', '~> 0.3'