
pod 'TTTAttributedLabel'
pod 'AsyncImageDownloader', '~> 1.0.0'
pod 'DMActivityInstagram', '0.0.3'
pod 'Foursquare-iOS-API', '~> 2.0'
pod 'Reachability', '~> 3.1.1'
pod 'FlatUIKit'
pod 'Facebook-iOS-SDK', '~> 3.12.0'
pod 'DYRateView', '~> 0.0.2'
pod 'UIImage-Helpers'
